### ISSUE TITLE
心 character is not displaying

### ISSUE THREAD

**Issue by splch** [Dixin/Etymology#133] opened 2020-08-19 00:17 UTC
Hi, I tried viewing the etymology of 心, but the website threw an error.

**Comment by Dixin** [comment] 2020-08-19 00:21
Thank you for reporting this. However I cannot reproduce the issue. Please see the screenshot. 

@splch What operating system and what browser are you using? What is the browser version number?

![0ABF97C7-AC96-46CB-80CB-AE958C02F4A3](https://user-images.githubusercontent.com/1563770/90578014-105b5400-e177-11ea-9194-02382528b6c7.png)

**Comment by splch** [comment] 2020-08-19 00:27
Thank you for the quick response! I just tried again and the results loaded. Before it had sent this though:
![image](https://user-images.githubusercontent.com/25377399/90578331-e8202500-e177-11ea-8fa5-49615ce60d15.jpeg)

I think my internet messed up for a brief moment. Sorry about that😅

**Comment by Dixin** [comment] 2020-08-19 00:29
@splch Glad it works. I am closing the issue. Please let me know if you have other issues.

**Closed by Dixin** 2020-08-19 00:29 UTC
