### ISSUE TITLE
Additional meaning to 和

### ISSUE THREAD

**Issue by burtsevdima** [Dixin/Etymology#114] opened 2019-03-31 07:11 UTC
It also means And, with

**Comment by UncleHanzi** [comment] 2019-05-09 08:16
Yes. I first try to put its most original meaning, the one related to the original pictograph. In my next update I will expand on the meanings. Thanks for the comment.

**Comment by Dixin** [comment] 2019-05-09 09:06
Reopen bug. Let’s close a bug when it’s fix is deployed and verified.

**Comment by UncleHanzi** [comment] 2019-05-10 01:49
When I give a meaning for a character，up till now, I try to give the original form and the original meaning 本相本意 . It will be a long time before I have extensive descriptions for the meanings of all 15,000 characters.  This should probably be considered an enhancement, not a bug. You will find the same limitations for most characters.

**Comment by Dixin** [comment] 2019-05-10 02:50
If it is an enhancement, we close the issue when the enhancement is deployed and verified.

**Comment by UncleHanzi** [comment] 2020-08-31 21:04
Has been corrected in the Etymology file

**Comment by UncleHanzi** [comment] 2020-09-17 03:34
I think it is OK now.

**Comment by UncleHanzi** [comment] 2020-11-19 02:59
Made it more clear in latest etymology table.

**Comment by UncleHanzi** [comment] 2020-11-19 03:00
Fixed in latest etymology table

**Closed by UncleHanzi** 2020-11-19 03:00 UTC
